# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myuser # Ganti dengan username PostgreSQL Anda
  password: mypassword # Ganti dengan password PostgreSQL Anda
  host: localhost

development:
  <<: *default
  database: myapp_development # Ganti dengan nama database Anda

test:
  <<: *default
  database: myapp_test # Ganti dengan nama database Anda

production:
  <<: *default
  database: myapp_production # Ganti dengan nama database Anda
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
